# Minimal Nav2 parameters for MBot
# Generated based on Nav2 default configurations. Adjust as necessary.
amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    min_particles: 100
    max_particles: 2000
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    tf_broadcast: true
    laser_min_range: 0.0
    laser_max_range: 30.0
    laser_max_beams: 360
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 2
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    initial_pose: [0.0, 0.0, 0.0]

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_time.xml"
    plugin_lib_names: ["nav2_compute_path_to_pose_action_bt_node",
                      "nav2_follow_path_action_bt_node",
                      "nav2_recovery_node_bt_node",
                      "nav2_wait_action_bt_node" ]

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_vel_x: 0.0
    max_vel_x: 0.5
    max_vel_theta: 1.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      goal_checker_name: "general_goal_checker"

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

behavior_server:
  ros__parameters:
    use_sim_time: false
    reactivate_after_error: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_footprint
      update_frequency: 5.0
      publish_frequency: 2.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_footprint
      update_frequency: 2.0
      publish_frequency: 1.0
      width: 20.0
      height: 20.0
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
