slam_toolbox:
  ros__parameters:
    # Core frames / topics
    odom_frame: odom            # Must match your odometry frame
    map_frame: map              # Global frame you want Nav2 to use
    base_frame: base_footprint  # Robot base TF frame
    scan_topic: /scan           # Laser topic

    # Run in localization-only mode (no map updates)
    mode: localization

    # Pose-graph to load (generated during mapping).  Adjust path.
    # Example: /home/mbot/mbot_ws/src/mbot_navigation/maps/office
    # Leave empty to rely purely on incoming /map topic.
    map_file_name: ''

    # Publish map→odom transform at 20 Hz
    transform_publish_period: 0.05

    # Keep scan matching enabled for tighter localization
    use_scan_matching: true

    # Disable loop closing while localizing
    do_loop_closing: false

    # Keep CPU load reasonable
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0

    # Solver configuration (defaults are fine, but explicit is clear)
    solver_plugin: solver_plugins::CeresSolver
