/**:
    ros__parameters:
        image_transport: raw
        family: Custom48h12
        size: 0.090                # default size if sizes[] omitted (not used here since we define sizes)
        max_hamming: 0

        detector:
            threads: 1
            decimate: 2.0
            blur: 0.0
            refine: True
            sharpening: 0.25
            debug: False

        pose_estimation_method: "pnp"

        tag:
            ids:   [1,  2,  3,  4,  5,  6,  7,  8,  9,  10,  20,  30,  40,  50,  60,  70,  80,  90]
            sizes: [0.090, 0.090, 0.090, 0.090, 0.090, 0.090, 0.090, 0.090, 0.090,
                    0.018, 0.018, 0.018, 0.018, 0.018, 0.018, 0.018, 0.018, 0.018]
